# Generated by Django 5.2.3 on 2025-07-01 10:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Component name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Component description')),
                ('business_function', models.TextField(help_text='Business function description')),
                ('component_type', models.CharField(choices=[('service', 'Service'), ('database', 'Database'), ('api', 'API'), ('frontend', 'Frontend'), ('middleware', 'Middleware'), ('external_service', 'External Service')], help_text='Type of component', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('is_active', models.BooleanField(default=True, help_text='Whether component is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Flow name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Flow description')),
                ('version', models.CharField(default='1.0.0', help_text='Flow version', max_length=50)),
                ('yaml_content', models.TextField(blank=True, help_text='YAML representation of the flow')),
                ('is_active', models.BooleanField(default=True, help_text='Whether flow is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlowComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_x', models.FloatField(default=0.0, help_text='X position in the flow diagram')),
                ('position_y', models.FloatField(default=0.0, help_text='Y position in the flow diagram')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Flow-specific configuration as JSON')),
                ('component', models.ForeignKey(help_text='Associated component', on_delete=django.db.models.deletion.CASCADE, related_name='flow_instances', to='core.component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(help_text='Associated flow', on_delete=django.db.models.deletion.CASCADE, related_name='flow_components', to='core.flow')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_type', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('tcp', 'TCP'), ('udp', 'UDP'), ('database', 'Database'), ('message_queue', 'Message Queue'), ('file_system', 'File System'), ('api', 'API')], help_text='Type of connection', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Connection metadata as JSON')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(help_text='Associated flow', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.flow')),
                ('source_component', models.ForeignKey(help_text='Source component', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='core.flowcomponent')),
                ('target_component', models.ForeignKey(help_text='Target component', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='core.flowcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Impact severity level', max_length=20)),
                ('analysis_results', models.JSONField(default=dict, help_text='Detailed analysis results as JSON')),
                ('recommendations', models.TextField(blank=True, help_text='Recommended actions')),
                ('affected_component', models.ForeignKey(help_text='Component being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='impact_analyses', to='core.component')),
                ('affected_components', models.ManyToManyField(blank=True, help_text='Components that would be affected', related_name='impacted_by', to='core.component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(help_text='Associated flow', on_delete=django.db.models.deletion.CASCADE, related_name='impact_analyses', to='core.flow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Runbook name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Runbook description')),
                ('version', models.CharField(default='1.0.0', help_text='Runbook version', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether runbook is active')),
                ('component', models.ForeignKey(help_text='Associated component', on_delete=django.db.models.deletion.CASCADE, related_name='runbooks', to='core.component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['component__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Step name', max_length=255)),
                ('description', models.TextField(help_text='Step description')),
                ('action_type', models.CharField(choices=[('shell_command', 'Shell Command'), ('api_call', 'API Call'), ('database_query', 'Database Query'), ('file_operation', 'File Operation'), ('notification', 'Notification'), ('manual_step', 'Manual Step')], help_text='Type of action', max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Action parameters as JSON')),
                ('order', models.PositiveIntegerField(help_text='Step order within the runbook')),
                ('estimated_duration', models.PositiveIntegerField(default=5, help_text='Estimated duration in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('is_critical', models.BooleanField(default=False, help_text='Whether this step is critical for the procedure')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('runbook', models.ForeignKey(help_text='Associated runbook', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.runbook')),
            ],
            options={
                'ordering': ['runbook', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['component_type'], name='core_compon_compone_96a9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['is_active'], name='core_compon_is_acti_91bf97_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['is_active'], name='core_flow_is_acti_611331_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='flowcomponent',
            index=models.Index(fields=['flow'], name='core_flowco_flow_id_8fda92_idx'),
        ),
        migrations.AddIndex(
            model_name='flowcomponent',
            index=models.Index(fields=['component'], name='core_flowco_compone_3e8337_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowcomponent',
            unique_together={('flow', 'component')},
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['flow'], name='core_connec_flow_id_23e63a_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['connection_type'], name='core_connec_connect_ebe592_idx'),
        ),
        migrations.AddIndex(
            model_name='impactanalysis',
            index=models.Index(fields=['flow', 'severity'], name='core_impact_flow_id_4306e3_idx'),
        ),
        migrations.AddIndex(
            model_name='impactanalysis',
            index=models.Index(fields=['affected_component'], name='core_impact_affecte_bae47f_idx'),
        ),
        migrations.AddIndex(
            model_name='runbook',
            index=models.Index(fields=['component', 'is_active'], name='core_runboo_compone_c45aaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='runbook',
            unique_together={('component', 'name', 'version')},
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['runbook', 'order'], name='core_step_runbook_986696_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['action_type'], name='core_step_action__29dd64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('runbook', 'order')},
        ),
    ]
