# Generated by Django 5.2.3 on 2025-07-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='kpis',
            field=models.JSONField(blank=True, default=list, help_text='Key Performance Indicators for this component'),
        ),
        migrations.AddField(
            model_name='component',
            name='owned_by',
            field=models.CharField(blank=True, help_text='Team or organization that owns this component', max_length=255),
        ),
        migrations.AddField(
            model_name='connection',
            name='flow_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external_user_triggered', 'External User Triggered'), ('external_system_triggered', 'External System Triggered')], default='internal', help_text='Type of flow (internal, external_user_triggered, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='connection',
            name='source',
            field=models.CharField(blank=True, help_text='Source description for the flow', max_length=255),
        ),
        migrations.AddField(
            model_name='connection',
            name='target',
            field=models.CharField(blank=True, help_text='Target description for the flow', max_length=255),
        ),
        migrations.AddField(
            model_name='flow',
            name='system_name',
            field=models.CharField(blank=True, help_text='System name for this flow', max_length=255),
        ),
        migrations.AddField(
            model_name='flow',
            name='system_purpose',
            field=models.TextField(blank=True, help_text='Purpose and objective of the system'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('tcp', 'TCP'), ('udp', 'UDP'), ('database', 'Database'), ('message_queue', 'Message Queue'), ('file_system', 'File System'), ('api', 'API'), ('internal', 'Internal'), ('external_user_triggered', 'External User Triggered')], help_text='Type of connection', max_length=50),
        ),
    ]
